### ISSUE TITLE
Classes are not taken in account in formulas when classes compendium is translated with Babele

### ISSUE THREAD

**Issue by aldarion-jdr** [foundryvtt-starfinder/foundryvtt-starfinder#1004]
**Describe the bug**
Modules : Babele + sfrpg-fr-translation (https://github.com/aldarion-jdr/sfrpg-fr-translation)
When formulas use the variable @class, it refers to the english name of the class.
It doesn't work when the Babele translation is activated.
Ex : "Solarian" translate as "Solarien" and then this formula for Supernova doesn't seem to find the "Solarian level" :
_(1+@Class.solarian.levels)d6_

**To Reproduce**
1. activate the modules
2. create a new solarian character in french by adding the class named "Solarien"
3. add the class feature "Supernova (Sur)"
4. click on "Dégâts" on the Supernova row in the "Spécificités" tab
5. Damage formula adds 0 instead of level number

**Expected behavior**
Formula be able to refer classes even when translated (maybe by using settings in the localization files?)

**Screenshots**
![image](https://user-images.githubusercontent.com/68708803/224505618-4356ad5c-ef39-4879-b194-873136ce1cdb.png)

![image](https://user-images.githubusercontent.com/68708803/224505641-377e007b-4800-44fd-a33b-029b0d9bcb29.png)

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: all+Foundry app
 - Foundry Version: 10.291
 - SFRPG Version: 0.22.1

**Additional context**
I'm afraid that other formula use translated references, with other conpendiums or sheets.

**Comment by LebombJames** [comment]
I thought we already fixed this. Can you check the class item in the console (Import it to the sidebar and run `game.items.getName("Solarien")`) and see what `system.slug` is?

**Comment by aldarion-jdr** [comment]
system.slug: "solarien"

**Comment by LebombJames** [comment]
Can you try after dragging a fresh copy of the class from the compendium?

**Comment by aldarion-jdr** [comment]
Sorry but drag to where?
Compendium FR > actor sheet (can do but I made a special new actor for the issue this afternoon)
Compendium FR > world items? Just did a new one in order to respond to the system.slug

**Comment by LebombJames** [comment]
Either, if you drag from the sidebar to character, test if modifiers work. If you drag to the sidebar, test if the slug is correct. Regardless, if you did the latter already, something *is* wrong

**Comment by aldarion-jdr** [comment]
Re-did both, same problem, Solarian levels are not counted when translation module is active.
Should I have system.slug: "solarian" or system.slug: "solarien"?
I still have system.slug: "solarien".

**Comment by LebombJames** [comment]
I have literally just spotted the issue, will PR in a second

**Comment by aldarion-jdr** [comment]
That's weird, I don't get why the slug is translated as the compendium Babele translation only translate the name and description of the classes.
Maybe it's in the fr locale? Did not spot anything before posting...

**Comment by aldarion-jdr** [comment]
Ah ok great !!!

**Comment by LebombJames** [comment]
It works fine for me now, so I suspect its something wrong with your Git environment. Our formulas for Supernova looks different too (this is at level 7), which means I'm on a later build
![image](https://user-images.githubusercontent.com/77904738/224515324-e737a42c-6205-4547-9ec5-5f3cdfa53d34.png)

**Comment by aldarion-jdr** [comment]
I just took the items.js file, maybe I should get everything?

**Comment by LebombJames** [comment]
It's always good to be running on the latest development build

**Comment by aldarion-jdr** [comment]
Well thats very weird... I have the correct display I think, but still 1d6 instead of 2d6 :
![image](https://user-images.githubusercontent.com/68708803/224515750-19d71c74-a148-4f78-9ef0-4a21ea18fe32.png)

**Comment by aldarion-jdr** [comment]
Just to be sure, do you also use the french Babele compendiums translation for your tests?

**Comment by aldarion-jdr** [comment]
![image](https://user-images.githubusercontent.com/68708803/224515842-c0e81383-2699-4c6b-9e1c-0a0f29d8295f.png)

**Comment by LebombJames** [comment]
What did you change? 😆

**Comment by aldarion-jdr** [comment]
Deactivated the Babele module ^^
Remove french translated class and active trait and put the english ones.

**Comment by LebombJames** [comment]
You still aren't on the latest development build though, I can tell by the height of the items on the sheet
![image](https://user-images.githubusercontent.com/77904738/224516012-35600782-b822-4599-ad3f-d077c777ddf3.png)
Should be small like this

**Comment by aldarion-jdr** [comment]
I'm using font height 6 not 5. That's why I think.

**Comment by aldarion-jdr** [comment]
Babele french module activated + french compendiums items : don't work.
Babele french module activated + english compendiums items : works.
![image](https://user-images.githubusercontent.com/68708803/224516128-58d843dc-7625-437f-84ad-e447a9385b82.png)

**Comment by LebombJames** [comment]
It's not due to font size, it was a very deliberate CSS change. The best course of action here is to do pull from development to ensure you have all the latest changes. I've checked and double checked and it works for me, so I don't know what else to recommend

**Comment by aldarion-jdr** [comment]
I'll try to get it right and keep you updated.

**Comment by aldarion-jdr** [comment]
I can't get the system to work. I miss sfrpg.css and styles/tippy.css in the "src" directory.
If I use the old one I of course have the display issue.
Nervertheless it shouldn't change the way formulas are used.

In your screenshot you have "Solarien", but the sheet is not translated. maube you're not using the fr locale?

**Comment by LebombJames** [comment]
That was with the translation turned off after I was done testing. Copying files from src/ isn't a great way to use the system, instead, follow the guide in contributing.md on how to create and build a local version of the system

**Comment by aldarion-jdr** [comment]
I figure out something : it works with "Solarien fr"+"Supernova en" but not with "Solarien fr" + "Supernova fr". In your screenshot you have "Supernova en" (Su in Sur in fr).
![image](https://user-images.githubusercontent.com/68708803/224517854-a2293d7c-3894-4bd6-a047-a5e49724c078.png)

**Comment by aldarion-jdr** [comment]
Both with french core translation.

**Comment by LebombJames** [comment]
Fresh class and supernova
![image](https://user-images.githubusercontent.com/77904738/224517928-8c036971-42d5-44ac-a72c-d22c6be9636b.png)

**Comment by aldarion-jdr** [comment]
Well that's crazy !
I have games in a few days, I don't want to break my worlds before it.
Glad to see it works on your end ! I'll wait the next update ;)
Thank you for your time and debug skills !

**Comment by aldarion-jdr** [comment]
Hello LebombJames !

Work pretty well now !
Thank you !

Le dim. 12 mars 2023 à 01:38, LebombJames ***@***.***> a
écrit :
