### ISSUE TITLE
Item hardness is not being calculated correctly

### ISSUE THREAD

**Issue by wildj79** [foundryvtt-starfinder/foundryvtt-starfinder#1027]
**Describe the bug**
An items hardness is supposed to be equal to 5 + item level or 5 + (2 * item level) if it's sturdy. Currently, it seems to always be equal to 2 * item level. See p. 409, CRB for rules reference. Also see https://aonsrd.com/Rules.aspx?ID=245.

**To Reproduce**
Open an item, and change the item level. See that the hardness isn't calculating correctly.

**Expected behavior**
The item's hardness should be calculated at 5 + item level or 5 + (2 * item level) if marked sturdy.

**Screenshots**
![image](https://user-images.githubusercontent.com/2126857/227627606-5f7f0b5f-6a02-4d43-9972-b2448030d7c5.png)
The hardness in the above image should be 6, since it's level 1.

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox v111.0.1 (64-bit)
 - Foundry Version: 10.291
 - SFRPG Version: tested on 0.20.3, but should be applicable on the current version

**Comment by wildj79** [comment]
Fix should be pretty simple. The formula on line 130 of src/module/item/sheet.js is wrong. Just replace:
```js
data.placeholders.hardness = this.parseNumber(itemData.attributes.hardness, 5 + itemData.attributes.sturdy ? 2 * itemLevel : itemLevel);
```
with:
```js
data.placeholders.hardness = this.parseNumber(itemData.attributes.hardness, itemData.attributes.sturdy ? 5 + (2 * itemLevel) : 5 + itemLevel);
```

The current implementation will always return `2 * itemLevel` since the ternary will always be truthy.

**Comment by wildj79** [comment]
Just to clarify on the numbers. You'll notice that the item pictured is a weapon. Technically, this should be considered "sturdy", but when I took the screenshot, I hadn't selected "sturdy" in the description. Technically the hardness should be 7 because of that, but the HP isn't correct for being "sturdy", so I left it at 6.

**Comment by Dosendusche** [comment]
Idk man this feels kind of weird since you already did the work and the only thing missing was the PR... anyway the PR is now created
