### ISSUE TITLE
Add toggle button to condition feats

### ISSUE THREAD

**Issue by lstar** [foundryvtt-starfinder/foundryvtt-starfinder#1031]
I would like to be able to toggle the feat or all the modifiers of a condition feat from the modifiers tab, rather than have to edit the feat and check/uncheck the modifiers within.
![AddCheckBox](https://user-images.githubusercontent.com/753407/227809505-0a5fc618-5f42-4a65-864b-8297fead4418.png)

**Comment by Dosendusche** [comment]
should be fixed by this: https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/995
