### ISSUE TITLE
Armor upgrade displaying incorrect allowed armor in sheet.

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#1052]
On sheet, the Armor upgrade item displays the allowed armor on it. However it is only displaying Power Armor, no matter what's set in the item.

![image](https://user-images.githubusercontent.com/60759323/230736824-4d419d39-5823-4fe0-875c-a462b498bac1.png)

 - SFRPG Version: Dev Branch

**Comment by ian612** [comment]
This might be a bug with your UI module. I can select any allowed armor type for armor upgrades.

![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/34078802/6bf7e8c2-0d02-4164-be2f-be51bbfb675a)

On the left are jump jets, on the right is a jetpack, I could modify it to any and it shows up properly.
![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/34078802/67efa012-f01e-4921-8f90-b403119d6d71)

**Comment by ian612** [comment]
Ah wait I see, it's not functioning correctly on the _character_ sheet, not the item sheet.
![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/34078802/fb693f70-825a-40af-9071-ab26da43d861)

I'll look into it
