### ISSUE TITLE
Custom Spell DC field under spellbook

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#1053]
A field for a custom Spell DC at the top of the spellbook tab for level 0 spells, with the others calculated off that. This would primarily be used for NPC sheets to easily modify all their spell DCs.

![image](https://user-images.githubusercontent.com/60759323/230738004-6658d6bd-f430-4afb-9755-80766bdff6ed.png)
Somewhere here.

**Comment by LebombJames** [comment]
NPC's already have the Base Spell DC field on the attributes tab
