### ISSUE TITLE
Sniper alternate class feature

### ISSUE THREAD

**Issue by danimrath** [foundryvtt-starfinder/foundryvtt-starfinder#1088]
**What item is incorrect/missing?**
The sniper alternate class feature for operative is missing the modifiers for damage and skill bonuses.

(1 - (min(1, floor(@classes.operative.levels / 3))))d3 + (1 + floor((@classes.operative.levels - 3) / 2))d6

https://www.aonsrd.com/AltClassFeatures.aspx?ID=32

**0.23.0**

**Comment by LebombJames** [comment]
Was closed by #1159
