### ISSUE TITLE
NPC equipment proficiency update bug

### ISSUE THREAD

**Issue by ian612** [foundryvtt-starfinder/foundryvtt-starfinder#1098]
**Describe the bug**
Dropping weapons onto an NPC from the items tab changes the proficient/equipped status on the sidebar item instead of the copy dropped onto the NPC. Only seems to happen on development, v0.24. Not reproducable on release v0.23.

**To Reproduce**
Create an NPC and weapon item in the sidebar, ensure that the Proficient box is not checked. Drop the weapon onto the npc sheet. View the item details on the NPC sheet and in the sidebar.

**Expected behavior**
Proficiency and equipped status should stay the same for the original item in the sidebar, and be updated on the copy placed on the NPC sheet.

**Screenshots**

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: electron app (0.24), Firefox (0.23)
 - Foundry Version:  10.291
 - SFRPG Version: 0.24

**Additional context**

**Comment by ian612** [comment]
Might be related to this commit?
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/commit/b42caec63a9963b7d1a92f8220608b9f16696284

**Comment by LebombJames** [comment]
If it is because `createEmbeddedDocuments`, then it's been a bug for several years 😂
