### ISSUE TITLE
Sickened condition also applies -2 to non-weapon damage

### ISSUE THREAD

**Issue by Beff42** [foundryvtt-starfinder/foundryvtt-starfinder#1114]
When a PC is sickened and has the condition switched on in the character sheet, they receive -2 on every type of damage they roll. The sickened condition states though, that only WEAPON damage gets a -2.

**How to reproduce:**
Create a player character, give them a weapon, a damage dealing spell and a serum of healing
Apply the condition 'Sickened' in the Modifiers tab.
Roll damage with the weapon, roll damage with the spell, roll the healing from the serum.

**Expected behavior**
The weapon damage should get -2.
The spell damage and the serum of healing should be unaffected of the condition.

**Actual behavior**
The weapon damage, the spell damage and the serum of healing all get -2 applied.

**Screenshots**
![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/83531917/1acd4a2a-f6dc-4bb5-879f-8aa800e7569b)

**Technical details (please complete the following information):**
 - OS: Win 10
 - Browser: na, running foundry server app
 - Foundry Version: 10.291
 - SFRPG Version: 0.23.0

**Comment by Iankid** [comment]
This may be an issue with the fact we are missing a Weapon Attack/Damage modifier, and instead just skip straight into several Specific Weapon attack/damage modifiers

**Comment by ian612** [comment]
I took a look at this, we do have modifiers for melee/ranged weapon damage, they're just labelled a little ambiguously as "Ranged Damage" and "Melee Damage". In the modifiers code, these translate to RANGED_DAMAGE and MELEE_DAMAGE.

The relevant code below from **item.js** shows RANGED_DAMAGE and MELEE_DAMAGE are only allowed on items with the ranged weapon attack ("rwak") and melee weapon attack ("mwak") properties.
```
if (["msak", "rsak"].includes(this.system.actionType) || (this.type === "spell"  && this.system.actionType === "save")) {
            acceptedModifiers.push(SFRPGEffectType.SPELL_DAMAGE);
        } else if (this.system.actionType === "rwak") {
            acceptedModifiers.push(SFRPGEffectType.RANGED_DAMAGE);
        } else if (this.system.actionType === "mwak") {
            acceptedModifiers.push(SFRPGEffectType.MELEE_DAMAGE);
        }
```

I'll update the label on the modifiers to be more clear, and fix the sickened condition in the compendium to resolve this.
