### ISSUE TITLE
starsinger archetype missing

### ISSUE THREAD

**Issue by charlietakethetrench** [foundryvtt-starfinder/foundryvtt-starfinder#1134]
Starsinger Archetype from [Starfinder #47: Nightmare Scenario pg. 45] (https://paizo.com/products/btq02asc?Starfinder-Adventure-Path-47-Nightmare-Scenario)

Nethys link: https://aonsrd.com/ArchetypeDisplay.aspx?ItemName=Starsinger

My player wanted to use this archetype but it's not in the archetype compendium, maybe because it's not from a core book and from an adventure path. 

If there is some way to add it that would be helpful, but I understand if you don't officially support adventure path content. 

Thanks for all that you do!

**Comment by Iankid** [comment]
We do support them. AP stuff just tends to can passed by accidentally. easier to grab the mainline rulebooks.
