### ISSUE TITLE
Prototype Token Resources 

### ISSUE THREAD

**Issue by JonDemand** [foundryvtt-starfinder/foundryvtt-starfinder#1144]
**Describe the bug**
in V11.299 when you edit the resource bars on the prototype token (HP/SP etc).  if you close and go back in,  the options previously chosen no longer show up

**To Reproduce**
Amend bars on prototype token,  update token,  and re-open settings and go back to resouce tab

**Expected behavior**
Should display the previous choices

**Screenshots**
Screenshot shows what happens when you re-open the resource tab after choosing bar settings (Always display HP/SP on Navasi)

**Technical details (please complete the following information):**
 - OS: Windows 11
 - Browser: Electron App
 - Foundry Version: V11.299
 - SFRPG Version: 0.25.0 Dev

**Additional context**
![v11299_resource_bug](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/83959698/bce8030e-a590-434f-8538-063c0bd894b2)

**Comment by ian612** [comment]
I think this was a core Foundry bug, but it looks like it's been fixed in the latest release. It's working fine for me on 11.301.

https://foundryvtt.com/releases/11.301
https://github.com/foundryvtt/foundryvtt/issues/9551
