### ISSUE TITLE
Dropped item not updating

### ISSUE THREAD

**Issue by Beff42** [foundryvtt-starfinder/foundryvtt-starfinder#1161]
**How to reproduce:**
- have an actor on a scene (reproducible with both, PCs and NPCs)
- open the actor sheet and drop an item from the inventory to the scene
- now open the container sheet of the dropped item and drag it into an actor inventory

**Expected behavior:**
The item should appear in the actor inventory. It should vanish from the container in the scene. If the option'delete when empty' is selected, the container should vanish from the scene, once all items are transferred.

**Actual behavior:**
The item does appear in the actor inventory. But it does not vanish from the container in the scene. If the option'delete when empty' is selected, the container does not vanish from the scene.
After closing and reopening the container sheet from the scene, the item is gone and the container is empty.

**Screenshots**
![DroppedItem](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/83531917/6ddb864c-23b1-440b-94ea-28aa4f3abf6a)

**Technical details:**
 - OS: Windows 10
 - Browser: na (Foundry Server app)
 - Foundry Version: 11.302
 - SFRPG Version: 0.24.2

**Additional context:**
Tested on a completely new and empty world with no modules active, but I see this also on migrated worlds from v10 and it was already present in 0.24.1 (I'm not sure if it was present in older versions than that).

**Comment by ian612** [comment]
When you do this, is there an error in the console (on most browsers you can open it by pressing F12)? I suspect it's linked to the same issues causing https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/887 and https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/206

**Comment by Beff42** [comment]
Yes, you are right. There is a TypeError, find the log attached: localhost-1687506025799.log
[localhost-1687506025799.log](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/files/11846024/localhost-1687506025799.log)

**Comment by Proximitron** [comment]
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/blob/2d75a932fb4b5db8d673edaa2fbe70eedbbe4be9/src/module/actor/sheet/base.js#L1236C9-L1236C56

Has to be:

else item = parsedDragData.items[0];

Problem caused:
Taking dropped items is impossible because it says "toObject" on a generic object, as such simply not working.

**Comment by LebombJames** [comment]
Should be closed by #1315
