### ISSUE TITLE
Reductive Plating does not modify DR as it should

### ISSUE THREAD

**Issue by Ghostwish-debug** [foundryvtt-starfinder/foundryvtt-starfinder#1167]
**Describe the bug**
It appears that the drone mod, Reductive Plating, is not correctly modifying DR.

**To Reproduce**
Slap Reductive Plating into a drone mod slot with the lube of your choice, and watch as the DR does not change. 

**Expected behavior**
DR should change to its respective value, but it seems Reductive Plating does not modify, well, anything. I manually added in the DR modifyer

**Screenshots**
N/A

**Technical details (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser: Firefox
 - Foundry Version: 11 Stable Build 302
 - SFRPG Version: 0.24.2

**Additional context**
Skree.

**Comment by Iankid** [comment]
This can me more accurately stated as a compendium issue, rather then a bug it seems. There are gaps where older items don't yet have the bells of whistles of newer features. In this regard this is a really helpful issue post, and I'll address it soon.
