### ISSUE TITLE
Conditions items become in-removable on PC actor

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#1168]
Condition items become in-removable on PC actor, sometimes creating mess of condition icons. Seems to start when toggling condition multiple times. Issue seems to be limited to PCs. And only in an online environment, such as Forge. Local foundry does not produce this issue.
Exported sheet can have conditions toggled off normally within local foundry.

Addition: Bug might be a latency issue, as cleaning up the server made the issue happen less often.

![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/60759323/c370b7cc-2f46-4d48-abdc-9a77fcb499ea)

![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/60759323/d97919ea-d20f-4d1f-b688-d3449ef33ec7)
![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/60759323/33d2d68f-38f5-4d58-b7cc-11fa31ee6e30)
![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/60759323/acb92c13-36b9-4012-8d5b-cb9ffb2b6a71)

 - Tested with all modules disabled, on new actor
 - SFRPG Version: Dev branch

**Comment by Beff42** [comment]
I saw this in my game on Tuesday, we do not use Forge.
One of my players had this issues. Workaround was to copy his character and removing the conditions from the right click menu on the token. Trying to remove the conditions from the character sheet made them unremovable again.
I'll try to reproduce this and might update with more info.

Technical details:

OS: Windows 10
Browser: I don't know which browser the player used, but it was also reproducible locally on my Foundry App
Foundry Version: 11.302
SFRPG Version: 0.24.2

**Comment by LebombJames** [comment]
#1176 partially solves this but it appears to me that this is a core bug: https://github.com/foundryvtt/foundryvtt/issues/9672#issuecomment-1605194277
