### ISSUE TITLE
Grenade launcher using grenades as ammo

### ISSUE THREAD

**Issue by Madfors** [foundryvtt-starfinder/foundryvtt-starfinder#1187]
Problem:
Grenade launchers don't use any ammo at all right now, and players must track their grenades manually. It also leads to unability of separated animations for grenade launchers.

Probable solution:
Implement grenades as ammunition, though it will probably require rework of whole weapon ammo system, cause currently one weapon could have one type of ammo

**Comment by ian612** [comment]
Duplicate of https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/960, for tracking/closeout purposes

**Comment by ian612** [comment]
Closing as this is a duplicate of #960
