### ISSUE TITLE
Multiple TypeErrors, for Actors in 'Not Started' Combat

### ISSUE THREAD

**Issue by Beff42** [foundryvtt-starfinder/foundryvtt-starfinder#1189]
**Describe the bug**
Adding and removing combatants to a combat before it is started throws errors.

**How to Reproduce**
Add a PC or NPC from the Compendium into your Scene (tested with Obozaya and Aeon Guard).
Toggle combat with right click on the actor. As long as the combat is not started, adding a combatant (sometimes also removing it) or rolling for initiative will throw a TypeError (due to a missing combatantId).

**Expected behavior**
As a user I want to add combatants and roll for initiative before I roll for combat. I would like to be the log free of errors, so I can be sure everything is working smoothly.

**Screenshots**
![Missing CombatantId](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/83531917/0ec3f3fd-f994-4071-9aff-37c621b3d8d1)

**Technical details (please complete the following information):**
 - OS: Windows 11
 - Browser: Electron app
 - Foundry Version: 11.304
 - SFRPG Version: 0.24.2

**Comment by LebombJames** [comment]
This is a core bug. Can reproduce on dnd5e.
