### ISSUE TITLE
Starship Power Core items not retaining checkbox state

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#1193]
Newly created Starship Power Core items are not able to retain the on toggle state for their supported ship sizes, once the item is closed.
This is only limited to created Power Cores. Ones drawn from compendium, or duplicated and edited from the compendium ones work.

![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/60759323/9b0af95a-d0b8-4c97-b720-3fe5a22823b9)

- Dev branch

**Comment by LebombJames** [comment]
Errors in the console!

**Comment by Iankid** [comment]
No errors shown
