### ISSUE TITLE
Weapon Specialization damage bonus added multiple times on weapons with multiple damage sections

### ISSUE THREAD

**Issue by mikegentry5** [foundryvtt-starfinder/foundryvtt-starfinder#1200]
**Describe the bug**
For weapons that have multiple damage sections, a character's weapon specialization bonus is being added multiple times -- once for each damage section.

**To Reproduce**
1) Create a basic melee weapon.
2) Give it 2 damage sections, each doing 1d6 damage.
3) Drop it in the inventory of a 3rd-level PC with the appropriate weapon specialization feat.
4) Equip the weapon and roll its damage, making sure both damage sections are checked.

**Expected behavior**
Total damage roll for the weapon would be 1d6 + 1d6 +3 (i.e., adding 3 to the total damage output of the weapon)

**Actual Behavior:**
Each damage section is rolled separately, and the weapon specialization bonus is added to each, resulting in a total damage roll of 1d6 + 3 + 1d6 + 3

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry Version: 10.303
 - SFRPG Version: 0.23.0

**Comment by Iankid** [comment]
Can you share the item/feature using this behavior? I don't doubt the need for this fix. I in fact know some future examples. But I'm curious what currently exists that can bring up this issue.

**Comment by mikegentry5** [comment]
It wasn't an existing item in the Compendiums. I was trying to create a
weapon to replicate the venom spur augmentation. (I know the existing
Compendium item with type==augmentation has attack & damage functionality
built in, but I wanted to try and recreate it as type==weapon for reasons,
not least that I wanted weapon specialization to apply to it).

So I created a weapon that does 1d6 P and 2d6 poison as separate damage
sections, and thus discovered the bug.

**Comment by Iankid** [comment]
As a meantime solution for that, I'd suggest using the compendium item, and copying the Specialization's formula into the damage field of the Venom Spur item.
