### ISSUE TITLE
Tech, Magic and hybrid items missing uses, and missing storage settings on Snapshot Sphere

### ISSUE THREAD

**Issue by Obtainedzer0** [foundryvtt-starfinder/foundryvtt-starfinder#1220]
**What item is incorrect/missing?**
Snapshot Sphere

**What book is the item from? What page is it on? If possible, include an Archives of Nethys link**
DC pg. 79, https://aonsrd.com/TechItems.aspx?ItemName=Snapshot%20Sphere&Family=None

**SFRPG system version**
0.23.0

**How is it incorrect?**
missing storage settings and no use button on the item.

**What correction should be made?**
add storage settings to hold ammunition and give Tech, Magic and hybrid items the ability to have actions applied to them and uses similar to feats or weapons.

**Comment by ian612** [comment]
For tracking/eventual closeout purposes, some parts of this are duplicated in https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/721
