### ISSUE TITLE
Problem with solarian in combat tracket

### ISSUE THREAD

**Issue by Carantin** [foundryvtt-starfinder/foundryvtt-starfinder#1223]
The solarian's data don' appear in the combat tracker 

**Screenshots**

![Captura](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/85190325/623efb16-5f7f-4965-afc2-72f567e05567)

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Foundry Version: 11.306
 - SFRPG Version:  0.24.2

**Comment by Iankid** [comment]
Can you test without modules? This is likely a UI mod issue.

**Comment by Carantin** [comment]
You right, Thank you
