### ISSUE TITLE
Sonic vulnerability not taken into account

### ISSUE THREAD

**Issue by Beff42** [foundryvtt-starfinder/foundryvtt-starfinder#1233]
**Describe the bug**
The vulnerability configured on the actor sheet does not work for Sonic damage. All other damage types seem to work fine.

**To Reproduce**
- create an actor
- under 'Damage Vulnerabilities' select 'Sonic'
- drag this actor in a scene and apply sonic damage with the right click option 'Apply damage' from chat

**Expected behavior**
The Sonic damage should subtract 1.5 times the damage rolled.

**Actual behaviour**
Sonic damage is applied as rolled, without modification.

**Screenshots**
![Sonic Vulnerability](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/83531917/66b8ad43-7c00-4ed0-94e1-8fb32dce8db4)

**Technical details (please complete the following information):**
 - OS: Win 11
 - Browser: electron app
 - Foundry Version: v11306
 - SFRPG Version: Tested on the development branch, fetched and pulled up-to-date as of today

**Additional context**
Was confirmed by two more people in Discord. Our wild guess is, that the double character 'So' for sonic damage might be the culprit, since all other (single character) damage types work as expected.

**Comment by Imper1um** [comment]
Pull Request #1244 will repair the issue.
