### ISSUE TITLE
DiceSFRPG.damageRoll does not return roll

### ISSUE THREAD

**Issue by niwith** [foundryvtt-starfinder/foundryvtt-starfinder#1235]
**Describe the bug**
In master/release DiceSFRPG.damageRoll does not return the roll, which causes the returned callbackResult to be undefined. 
In the development branch this issue was fixed in this commit: https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/commit/24a65d3ceee69a2a02b85e2669f0b2210675a273 

**Technical details (please complete the following information):**
 - SFRPG Version: v0.24.2

**Comment by LebombJames** [comment]
I don't know what you were trying to achieve with this issue. The problem is already fixed, and you even acknowledged so?

**Comment by niwith** [comment]
My apologies, I thought this change had been missed in a release, but re-reading the git history I must have been misunderstanding.

Thank you for inlcuding the fix in the latest release, working perfectly :)
