### ISSUE TITLE
encumbrance called before it is set in calculate-encumbrance

### ISSUE THREAD

**Issue by Imper1um** [foundryvtt-starfinder/foundryvtt-starfinder#1247]
Does not fix this error:
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/blob/de533d14e09c791f0966cc4c9f017fdd063eb7ab/src/module/rules/actions/actor/calculate-encumbrance.js#L11
`encumbrance` is called before it is created. It should be `data.encumbrance`

_Originally posted by @Imper1um in https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/1246#issuecomment-1677989777_

**Comment by LebombJames** [comment]
Fixed by #1251
