### ISSUE TITLE
Attack roll errors

### ISSUE THREAD

**Issue by Grizlug** [foundryvtt-starfinder/foundryvtt-starfinder#1264]
When rolling an attack, the figures pulled from BAB and Dex or Str modifier are wildly incorrect.  (25 dex bonus for a level 11 Mechanic) and similar figures for BAB

**To Reproduce**
I get this error on all creatures and characters in my game

**Expected behavior**
I think the expectation here is clear, the correct figure for BAB, Dex/Str modifiers in attack rolls

**Screenshots**

![bug report 1](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/124970500/575f81d9-ffb5-4fb7-9c29-f56a0da26271)

**Technical details (please complete the following information):**
 - OS:  Windows 10
 - Browser: chrome
 - Foundry Version: 11 build 305
 - SFRPG Version: 0.25.2

**Comment by Iankid** [comment]
Can you share one of these characters in the discord?

**Comment by Grizlug** [comment]
Will try right now.  Can you give me the server name?   Sent from Mail for Windows From: IankidSent: Wednesday, August 30, 2023 3:34 PMTo: foundryvtt-starfinder/foundryvtt-starfinderCc: Grizlug; AuthorSubject: Re: [foundryvtt-starfinder/foundryvtt-starfinder] Attack roll errors (Issue #1264) Can you share one of these characters in the discord?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Grizlug** [comment]
It looks like it is a module conflict causing the error.  I am re-installing the modules now to try to find which one.  Thanks for all the help and sorry I didn't think to check for module compatibility issues first
