### ISSUE TITLE
[Alien Archive 3] Missing Giant Space Tartigrade spaceship

### ISSUE THREAD

**Issue by deidril** [foundryvtt-starfinder/foundryvtt-starfinder#1285]
**What item is incorrect/missing?**
Giant Space Tartigrade

**What book is the item from? What page is it on? If possible, include an Archives of Nethys link**
AA3 page 40

**SFRPG system version**

(If the item is incorrect):
**How is it incorrect?**
It's missing in the spaceship compendium

**Comment by ilya-vasiuk** [comment]
Gwalhed was [added](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/734/files#diff-08a9fe51d59ee18d8517240d4521059ddef4fdfb4b4463344d95f3c101f8f321) some time before. And it's here in v0.26.1

**Comment by ian612** [comment]
Confirmed that Giant Space Tardigrade is in 0.26.1
