### ISSUE TITLE
[Alien Archive 3] Missing spaceship Gwahled

### ISSUE THREAD

**Issue by deidril** [foundryvtt-starfinder/foundryvtt-starfinder#1286]
**What item is incorrect/missing?**
Gwahled

**What book is the item from? What page is it on? If possible, include an Archives of Nethys link**
AA3 page 46

**SFRPG system version**

(If the item is incorrect):
**How is it incorrect?**
It's missing in the spaceship compendium

**Comment by ilya-vasiuk** [comment]
Gwalhed was [added](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/734/files#diff-3e70641d69ed32e86bf626600be1943d57159b3ac24515c021ff2408f88bdd89) some time before. And it's here in v0.26.1
