### ISSUE TITLE
Shaken Condition adds and additional -2 to attack rolls. 

### ISSUE THREAD

**Issue by Seanreck** [foundryvtt-starfinder/foundryvtt-starfinder#1295]
When you apply the shaken modifier to an actor PC or NPC, then that actor performs an attack, the resulting formula shows that the shaken penalty is added 2 times.  

**To Reproduce**
Enable the shaken modifier on an actor then make the attack with the actor.  Checking the formula and roll information will show that the shaken condition has been applied twice. 

**Expected behavior**
The shaken condition should only be applied one time and thus only a -2 not the -4 that is being received currently. 

**Screenshots**
![Foundry Shaken Error](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/49736304/56420d95-da2c-47f6-97c1-79c34f5355c2)

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome or on the application itself. 
 - Foundry Version: Build 315 Version 11 Stable
 - SFRPG Version: 0.25.2
**Additional context**
Noted by my players and reproduced by several and myself on the server.

**Comment by LebombJames** [comment]
Already fixed on the development branch
