### ISSUE TITLE
NPC-Sheet, the rolls do not work properly

### ISSUE THREAD

**Issue by skyly87** [foundryvtt-starfinder/foundryvtt-starfinder#1300]
No matter how you try, the rolls and attributes are not added together, so the NPC sheet is useless.
No error is displayed in the console, so something seems to have been forgotten on the NPC-Sheet that attributes, skills and modifiers are calculated together.
![NPC-Sheet](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/1340423/319a2140-8fb9-4834-9c96-06a3ba9a5c6f)

**Comment by ian612** [comment]
Yeah, this can be a little unintuitive but it does function that way on purpose. The NPC sheet does not add these values as this is the convention in all Paizo-provided stat blocks (see https://aonsrd.com/AlienDisplay.aspx?ItemName=Space%20Goblin%20Zaperator&Family=Goblin%20(Space), for example).

The skill bonuses are meant to be the only thing added to NPC rolls. If a skill is not listed, the attribute bonus is rolled instead. Things like AC bonuses from armor are likewise not added to NPCs, as Paizo's NPCs don't always follow the standard rule of 10 + Dex + AC mod. The values for skill roll and AC bonuses are just whatever is put in the field on the sheet directly.

If you want the values to automatically calculate in the expected way like a character does, you can make the NPC using a Character sheet.
