### ISSUE TITLE
Lv 1+ spells dragged from spellbook can't be cast using spell slot from macro bar

### ISSUE THREAD

**Issue by Theleruby** [foundryvtt-starfinder/foundryvtt-starfinder#1325]
**Describe the bug**
After a regular player drags a level 1+ spell from the spellbook to the macro bar and attempts to use it, they get a permission error. If the GM tries to use this macro, it casts the spell without using a spell slot.

**To Reproduce**
1. Create a character sheet for a Technomancer
2. Add "Jolting Surge" from the compendium to the spellbook
3. Drag "Jolting Surge" from the spellbook to the macro bar
4. Click it
5. Orange warning box appears - "You do not have permission to execute Macro "Jolting Surge"."

**Expected behavior**
The dialog "Jolting Surge: Spell Configuration" should appear, allowing you to select which spell slot you want to use for the spell, the same as if you'd gone into the character sheet to use the spell.

**Screenshots**
![image](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/assets/1058939/3c517a5a-a3ae-4d06-b8f9-0819a4cd272b)

**Technical details (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Foundry Version: 12.328
 - SFRPG Version: 0.26.0

**Additional context**
It is possible to work around this by manually creating a script macro looking something like e.g.:
```
const actor = game.users.get(game.userId).character;
const spell = actor.items.getName("Jolting Surge");
actor.useSpell(spell);
```
However we expected it to work without having to do this.

**Comment by Theleruby** [comment]
Some further observations:

1. I also tested this with "Remote Operation" (the player's other level 1 spell) and they were able to use the macro without the permission issue, but the spell slot dialog was still missing.
2. In the macro browser both spells were listed as having that player as "Author". However the player was only able to see the partially working macro Remote Operation in the macro browser; Jolting Surge wasn't visible at all to them. This matched with the apparent permission issue.

**Comment by LebombJames** [comment]
The permissions error is caused by the player role not having the permission to use macros, but the spell dialog is added in #1330
