### ISSUE TITLE
The entire Setting Compendium is blank

### ISSUE THREAD

**Issue by dickermax23** [foundryvtt-starfinder/foundryvtt-starfinder#1384]
**Describe the bug**
The entire compendium for setting is blank, the tabs like The Drift, or Triune is there. But when clicked, it's the title, And blank, nothing there at all.

**To Reproduce**
Open the Setting Compendium
**Expected behavior**
To be able to see the Compendium
**Screenshots**
![image](https://github.com/user-attachments/assets/e1cc398c-c93c-48ae-ad0a-ec73bd03d54e)

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry Version: 12.328
 - SFRPG Version: 0,26.1

**Additional context**

**Comment by levirak** [comment]
I can confirm that this is true for the top of development at the moment. Though in my local environment I can fix this entirely by forcing the cook process to push through the consistency errors. This should be resolved by #1361.

**Comment by ian612** [comment]
I'm going to close this as #1361 has been merged into development.
