### ISSUE TITLE
Custom Starfinder Chat Cards Do Not Hide Enemy Rolls 

### ISSUE THREAD

**Issue by lightnyn** [foundryvtt-starfinder/foundryvtt-starfinder#1386]
**Describe the bug**
I have been using the custom Starfinder chat cards for a few weeks now, but last week one of my players informed me that they could see everything the enemies were doing. I tested it out and found that the enemy name, what they were doing, and all their rolls were visible to all my players, and none of them have permissions above 'player'. This includes initiative and weapon/item/spell usage. I found that I could hide the card after the fact by right-clicking, but they were by default visible. When I switch back to the Foundry default chat cards everything hostile NPCs do is hidden by default again.

**To Reproduce**
Enable "Use custom Starfinder chat card" in Starfinder settings. Roll initiative or use any ability/weapon/spell from a hostile NPC.

**Expected behavior**
I expected the cards generated by hostile NPC actions to be hidden like how the default Foundry cards behave

**Technical details (please complete the following information):**
 - OS: Windows 11
 - Browser: Foundry vtt app, Brave, and Edge browswers
 - Foundry Version: 12.331
 - SFRPG Version: 0.26.1

**Comment by ian612** [comment]
Afaik this should be resolved by #1389 , once it gets merged.

**Comment by ian612** [comment]
Also for tracking purposes, this is likely the same root issue as #1385, so closing for now as a duplicate
