### ISSUE TITLE
[FEAT] Add Quick Roll information to Items & Chat Cards.

### ISSUE THREAD

**Issue by JayBWalker** [foundryvtt-starfinder/foundryvtt-starfinder#160]
Similarly to D&D Beyond or HeroLabOnline, Items could benefit greatly from having their most important information shown upfront on the character sheet without having to dig into the Edit side of things.

For example: Viewing an 'Unarmed Strike' Item under Equipment on a Character Page should display the total To-Hit Bonus for the Attack and the Roll Formula for the Damage (and perhaps also the damage type, in this case 'B' for Bludgeoning).

Spells meanwhile could indicate Range by type 'Short/Medium' etc as well as Standard Save DC.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Add Quick Roll information to Items & Chat Cards.](https://trello.com/c/AjBEXvLb/55-feat-add-quick-roll-information-to-items-chat-cards)

**Comment by ian612** [comment]
I was going to mention this as a feature request idea, but found this old post that was still open. Just wanted to comment that I think this would be really handy.

**Comment by Imper1um** [comment]
I think this was either wholly or partially implemented, at least on #1245 . Weapons now display their To Hit/Damage Rolls/Bonuses rather than "Attack" and "Damage" buttons.

**Comment by ian612** [comment]
Closed as part of old issue cleanup
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
