### ISSUE TITLE
[FEAT] Quick Roll Information

### ISSUE THREAD

**Issue by JayBWalker** [foundryvtt-starfinder/foundryvtt-starfinder#189]
Having some crucial values provide upfront under the collapsable info on Items would be extremely useful.

Such as: To Hit (total) Bonus, Damage, Save DC, etc.

[A super quick mock-up of what I mean](https://media.discordapp.net/attachments/716799568091807805/759680142527823892/unknown.png)

**Comment by Imper1um** [comment]
I think this was wholly or partially implemented, at least on latest.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
