### ISSUE TITLE
Values that can't be edited

### ISSUE THREAD

**Issue by CptTwinkie** [foundryvtt-starfinder/foundryvtt-starfinder#195]
After dragging a weapon to an NPC (tried with multiple weapons) that has a usage type set under Capacity & Usage. The type cannot be changed. Once I was able to work around this by restarting Foundry but it doesn't always work.

After dragging a feat to an NPC (tried with multiple feats) cannot set Recharge On under Feature Usage. I tried everything I could think of for this including setting an item the same as an existing item that had a recharge already set. It won't take any value.

```
FVTT 0.6.6
SFRPG 0.6.0.0
Modules 2 (Right-click Enabler, Search Anywhere)
```

**Comment by CptTwinkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Values that can't be edited](https://trello.com/c/Xypa4X6G/85-bugz-values-that-cant-be-edited)

**Comment by TimToxopeus** [comment]
"Capacity usage per" selector tag did not have a name property so its value was not being saved to the item. Fixed for Starfinder v0.6

**Comment by CptTwinkie** [comment]
I would point out the similar issue in the second half of the description...

> After dragging a feat to an NPC (tried with multiple feats) cannot set Recharge On under Feature Usage. I tried everything I could think of for this including setting an item the same as an existing item that had a recharge already set. It won't take any value.

**Comment by TimToxopeus** [comment]
It only takes numbers. Each time you click roll recharge, it will roll a 1d6 and tests if it is higher than the number filled into the recharge on field.

This is potentially a legacy 5e feature. @wildj79 do you know about this feature's history?

**Comment by wildj79** [comment]
@TimToxopeus It is a legacy holdover. It will need to be reworked to fit SFRPG better.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
