### ISSUE TITLE
Missing localisation for some elements

### ISSUE THREAD

**Issue by DocQuantic** [foundryvtt-starfinder/foundryvtt-starfinder#243]
Hi,
I realized that some elements are not localized in actor sheets. Here is the list of the one I found:

actor-features.html:
- l.7: Reaction

actor-inventory.html:
- l.21: {{section.label}} should be localised. Indeed, for some inventory lists, the title is not localized. I couldn't find the reason why. For instance, "Unmounted weapons" in the Weapons tab of the starship  sheet. I can provide a full list if needed.

starship-sheet-full.html:
- l.45: Statistics
- l.54: PCU
- l.62: BP
- l.69: Thresholds
- l.86: Movement

vehicle-sheet.html:
- l.15: Level
- l.24: Price
- l.32: Attacks
- l.51: Threshold
- l.56: Hardness
- l.79: Speed
- l.83: Drive
- l.90: Full
- l.97: MPH
- l.112: Width
- l.115: Feet
- l.119: Length
- l.122: Feet
- l.126: Height
- l.129: Feet
- l.136: Other Attributes
- l.140: Size
- l.152: Type and also the elements in the dropdown menu (couldn’t find the file)
- l.164: Cover
- l.176: Passengers
- l.187: Attacks and Modifiers

**Comment by TimToxopeus** [comment]
Unmounted weapons on the starship sheet are localized. See SFRPG.StarshipSheet.Weapons.NotMounted for the value. Section headers are localized in the code, you will find them in the sheet files, /module/actor/sheet/*.js, look for the _prepareItems() functions.

I think I have localized all of them by now. :)

**Comment by DocQuantic** [comment]
Ok sorry for that I just checked the html files. It looks like everything is ok now for the actors

**Comment by DocQuantic** [comment]
I noticed other missing localizations. I don't know if I should make a new issue.
Here is the list (I didn't find the file and the line for all of them):

item.js:
l.68: Passive 

sheet.js:
l.191: Equipped
l.191: Unequipped
l.192: Mounted
l.192: Not Mounted
l.215: Concentration
l.216: Spell Resistence
l.217: Dismissible

Augmentation sheet:
In the header, the type and the system of the augmentation are not localized.

Armor Upgrade sheet:
In the Details tab, armor types for allowed armors are not localized.

dice.js:
Advantage and Disadvantage are not localized. They are present at different lines of the file.

Chat Cards:
In the chat cards, “Skill check”, “Ability check” and “Save” are not localized.

**Comment by Alinarin** [comment]
Since issue still open, just find some else missed:
apps/add-edit-skill.html
- I.3 Ability
- I.15 Ranks
- I.21 Misc. Modifier
- I.28 Profession Name
- I.35 Skill Properties
- I.37 Class Skill
- I.40 Trained Only
- I.43 Armor Check Penalty
- I.47 Enabled
- I.52 Delete?

apps/spell-cast.html
- I.2
- I.5
- I.9 Cast at Level
- I.23 Consume Spell Slot?

apps/starship-role.html
- I.3 Ship's Role

classes/counter-management.html
- I.7 Graviton
- I.13 Photon

**Comment by Alinarin** [comment]
And some section-headers without localisation
items\starshipWeapon.html   line 49
items\vehicleAttack.html line 53
items\vehicleSystem lines 45,66,87

**Comment by ian612** [comment]
In the interest of closing out this issue, I'm going to repost everything that's been mentioned as checkboxes so they can be tracked as they're fixed.

actor-features.html:

- [x] l.7: Reaction

actor-inventory.html:

- [ ] l.21: {{section.label}} should be localised. Indeed, for some inventory lists, the title is not localized. I couldn't find the reason why. For instance, "Unmounted weapons" in the Weapons tab of the starship sheet. I can provide a full list if needed.

starship-sheet-full.html:

- [ ] l.45: Statistics
- [ ] l.54: PCU
- [ ] l.62: BP
- [ ] l.69: Thresholds
- [ ] l.86: Movement

vehicle-sheet.html:

- [ ] l.15: Level
- [ ] l.24: Price
- [ ] l.32: Attacks
- [ ] l.51: Threshold
- [ ] l.56: Hardness
- [ ] l.79: Speed
- [ ] l.83: Drive
- [ ] l.90: Full
- [ ] l.97: MPH
- [ ] l.112: Width
- [ ] l.115: Feet
- [ ] l.119: Length
- [ ] l.122: Feet
- [ ] l.126: Height
- [ ] l.129: Feet
- [ ] l.136: Other Attributes
- [ ] l.140: Size
- [ ] l.152: Type and also the elements in the dropdown menu (couldn’t find the file)
- [ ] l.164: Cover
- [ ] l.176: Passengers
- [ ] l.187: Attacks and Modifiers

item.js:

- [ ] l.68: Passive

sheet.js:

- [ ] l.191: Equipped
- [ ] l.191: Unequipped
- [ ] l.192: Mounted
- [ ] l.192: Not Mounted
- [ ] l.215: Concentration
- [ ] l.216: Spell Resistence
- [ ] l.217: Dismissible

Augmentation sheet:
- [ ] In the header, the type and the system of the augmentation are not localized.

Armor Upgrade sheet:
- [ ] In the Details tab, armor types for allowed armors are not localized.

dice.js:
- [ ] Advantage and Disadvantage are not localized. They are present at different lines of the file.

Chat Cards:
- [ ] In the chat cards, “Skill check”
- [ ] “Ability check”
- [ ] and “Save” are not localized.

apps/add-edit-skill.html

- [ ] I.3 Ability
- [ ] I.15 Ranks
- [ ] I.21 Misc. Modifier
- [ ] I.28 Profession Name
- [ ] I.35 Skill Properties
- [ ] I.37 Class Skill
- [ ] I.40 Trained Only
- [ ] I.43 Armor Check Penalty
- [ ] I.47 Enabled
- [ ] I.52 Delete?

apps/spell-cast.html

- [ ] I.2
- [ ] I.5
- [ ] I.9 Cast at Level
- [ ] I.23 Consume Spell Slot?

apps/starship-role.html

- [ ] I.3 Ship's Role

classes/counter-management.html

- [ ] I.7 Graviton
- [ ] I.13 Photon

And some section-headers without localisation

- [ ] items\starshipWeapon.html line 49
- [ ] items\vehicleAttack.html line 53
- [ ] items\vehicleSystem lines 45,66,87
