### ISSUE TITLE
Roll Initiative - extra clicks

### ISSUE THREAD

**Issue by drixtol** [foundryvtt-starfinder/foundryvtt-starfinder#262]
The roll initiative buttons require manually clicking for all characters. 

This changed in a recent version as before there was no pop up for a modifier. The modifier can not be bypassed like normal with a shift click

Version - 
0.7.9 Foundry
0.8.1 and 0.8.2
No add-on modules activated.

**Comment by ian612** [comment]
I believe this is working correctly now at the very least in dev (v0.25), probably 0.24 as well
