### ISSUE TITLE
Critical Rolls - Damage

### ISSUE THREAD

**Issue by Shwaazi** [foundryvtt-starfinder/foundryvtt-starfinder#310]
Unfortunately, it seems when adding a Critical Damage Formula, when an attack crits and damage is rolled from it, or with it, it will not display this Critical Damage Formula. In the compendium items, it appears to have that information displayed in the notes, however the notes do not show on the chat card either(unless there is an option I am missing).

Thank you for your time and effort!

**Comment by Shwaazi** [comment]
After fiddling around, it appears this is only an issue when using the quick roll. If you are using the standard rolling you are prompted to roll Normal or Critical damage.

**Comment by coppolaop** [comment]
Option to roll a critical damage is visible, but it not work. The damage is normal, not "doubled".

**Comment by ian612** [comment]
This doesn't appear to be an issue on 0.26.1, so I'm going to close it as fixed
