### ISSUE TITLE
Vechicle Data issues

### ISSUE THREAD

**Issue by drixtol** [foundryvtt-starfinder/foundryvtt-starfinder#352]
I checked two vehicles and the token names were incorrect.

{
    "name": "Police Cruiser",
....
 "token": {
        "flags": {},
        "name": "Goblin Junkcycle",

and

 "name": "Performance Cruiser",
...
    "token": {
        "flags": {},
        "name": "Motorcycle",

**Comment by rrenna** [comment]
Thanks for this.

**Comment by ian612** [comment]
I checked all the vehicles in the current build of the compendium, each has the correct prototypeToken name. This issue can probably be closed.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
