### ISSUE TITLE
Starship sheet crew as NPC option problem

### ISSUE THREAD

**Issue by KunYuL** [foundryvtt-starfinder/foundryvtt-starfinder#364]
When enabling crew as NPC on the Starship sheet, when assigning a gunner, it will ask to associate a skill to it. On a NPC Starship statblock, we are typically given only a single Gunnery +X bonus. 

Now when adding Piloting as a NPC skill check into the gunnery crew slot, it will do the same formula as for a PC, be it BAB or Skill rank whichever is highest, and DEX. The problem here is that it will try to pull those stats from a NPC crew that doesn't have them. 

The solution is to add a Gunnery bonus to NPC crew in the Gunner slot, that can be dictated as a flat bonus as opposed to determined by a formulae.

Another request related to this would be to have custom sheets for NPC Starships and Living Starships. Living Starships are awesome, it would so cool to have some integration for them. Once again, thank you for all you do ! The Starfinder community finds itself richer by your presence.
![image](https://user-images.githubusercontent.com/26071469/113518799-c2e4f900-9545-11eb-85d8-19c08f2d40bc.png)

**Comment by ian612** [comment]
This is present in 0.26.1, so I'm going to close it for now
