### ISSUE TITLE
Critical effect is not displayed

### ISSUE THREAD

**Issue by skyly87** [foundryvtt-starfinder/foundryvtt-starfinder#370]
At the Weapon Roll (attack and damage) dont let show the text field for critical effect into the chat.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
