### ISSUE TITLE
Class feature saving throws not using correct DC formula

### ISSUE THREAD

**Issue by supernovajm** [foundryvtt-starfinder/foundryvtt-starfinder#381]
Most class feature saving throws in starfinder have a DC of 
`10 + 1/2 class level + key ability score modifier.`
 It appears that the current default calculation is
`10 + full character level + key ability score modifier`

See example below using stellar rush
![image](https://user-images.githubusercontent.com/24704061/116764452-22bcab80-a9ef-11eb-861b-2a37f2f6fe20.png)

6 solarian levels (1 mystic level)
![image](https://user-images.githubusercontent.com/24704061/116764614-af676980-a9ef-11eb-86bd-2c744ac2e892.png)

14 charisma
![image](https://user-images.githubusercontent.com/24704061/116764443-1d5f6100-a9ef-11eb-9834-ee16d18f7a26.png)

should equate to a saving throw of 10+3+2 = DC15
but instead is 10+7+2=DC19
![image](https://user-images.githubusercontent.com/24704061/116764602-9f4f8a00-a9ef-11eb-9cb9-74e038069936.png)

The tricky part is the class levels vs character levels, because to my knowledge we have no way to identify which class a feat is associated with, so multi-class characters don't have a way to auto-calculate correctly anyway. But getting it right for single-class characters at least will cover a simple majority of cases.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
