### ISSUE TITLE
Summon Allies UCR should be a spell

### ISSUE THREAD

**Issue by ThroughlyDruxy** [foundryvtt-starfinder/foundryvtt-starfinder#453]
Summon Allies the UCR should be listed as a spell as that's how it's listed in all statblocks.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
