### ISSUE TITLE
Weapon accessories and fusions not adding their modifiers

### ISSUE THREAD

**Issue by TheFrontButtKid** [foundryvtt-starfinder/foundryvtt-starfinder#455]
Items listed as "weapon fusion" and "weapon accessory" do not add their modifiers to weapons rolls. When recreated as a hybrid item, the modifier does get added. Tested with nearly all Solarian crystals in the compendium and the only items at fault are the ones listed as "weapon fusion" or "weapon accessory".

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
