### ISSUE TITLE
Chat Roll colors do not change depending on roll type

### ISSUE THREAD

**Issue by CarolinaGuy89** [foundryvtt-starfinder/foundryvtt-starfinder#457]
In the Chat Window all roll types always appear blue, regardless of the chosen roll type.
Therefore, it is not possible for a GM to determine if a Player's roll was a public roll, or Private/Blind GM roll.

Tested in Starfinder 0.14.3, FVTT 0.8.9, with no active modules.

![SF_Roll_Colors](https://user-images.githubusercontent.com/25287857/141689249-7fcc6bb9-0c5e-43c4-bfef-b0bea50cf1e8.png)

**Comment by wildj79** [comment]
It looks like the system is overriding the core styling for this. It wasn't intentional, at least on my part. But, it's kind of a low priority fix, so it might be awhile. We're gonna have to fix some other CSS related issues for the upcoming Foundry v9 stable release anyway, so it'll probably be addressed at that point.

**Comment by Tarbarian** [comment]
The image below is a recreation of the above image in Foundry v9 (no modules), which shows that the roll method isn't even displayed in text anymore. So the DM can't tell what roll method was used whatsoever.

![image](https://user-images.githubusercontent.com/76751079/152592437-07ed6917-0cc8-4cf7-935c-013a8cf0e895.png)

**Comment by wildj79** [comment]
I've had an opportunity to look into this issue a little further, and I've figured out what is going on here. This is actually working, kind of. Foundry is setting a border color for the different roll modes, it's just that it's so subtle its almost unnoticeable (you basically have to know its there, and then after staring at the screen for a while you can just barely see it. It's kind of a purplish color. In fact, if you stare at the screenshot's in this issue hard enough, you can see it). It seems that the default color's used by foundry blends into the image background that we use on the chat cards. The fix should be pretty straight forward, we just need to adjust the color's to something that stands out a little more.

**Comment by Tarbarian** [comment]
I believe the image below shows better what you are talking about. This is taken from our friends over at PF1e. I personally only really care that there is a solid difference between public and private rolls, the difference between GM, blind, and self matter very little in my opinion. Perhaps a darker blue for the standard public rolls? 

![image](https://user-images.githubusercontent.com/76751079/169409489-8e8c6301-6225-4f98-b509-84579734b425.png)

**Comment by avagdumortesin** [comment]
In this, I have the public, GM, and Blind GM rolls, and have updated the colors to not use the image.
<img width="296" alt="Screen Shot 2022-06-10 at 11 43 10 PM" src="https://user-images.githubusercontent.com/55938242/173176770-08bbeabb-1f06-4b34-8046-f196ff6e8c9e.png">

I made the border around the two a bit larger to make them more visible, and the colors aren't being hidden by the background anymore.

I'm still looking at how to get the text for the type of roll to appear in the card.

**Comment by wildj79** [comment]
I'm reopening this one because it is only partially fixed. We now have a background color and new color's for the boarders, but we are still missing the textual cues that used to exist. We've determined that it's an upstream issue that is being looked into for foundry v10, so hopefully it'll be all worked out for that release.

**Comment by avagdumortesin** [comment]
Looks like the wording will be back with v10 Dev 2.
