### ISSUE TITLE
Item features update request in prep for TR compendium items

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#469]
As I work on the TR equipment compendium, these requested item type changes would help make a more complete listing for the equipment.

Marking fixed issues

DONE ---(General:
Usage update; allow usage per multiple minutes/hours/days.
E.G. “1/10 minutes”)---

DONE ---(Tech items:
Containers; Allow tech items to be containers)---

Power Armor:
Speed; this does exist, but powered armor replaces a PC's normal speed, rather than adjusts their original. 
Strength; this would be complex to add I can guess. This, once again, replaces the PC's normal stat. 
Size; replaces the PC's normal size 
capacity and usage; yep, it needs batteries
Bulk; needs to be negated from the carrying capacity while the item is equipped

Augmentations
Attack/Damage rolls; allow rolls on these items
Usage/capacity: needs adding

Weapons
DONE--( Specials tags; Buttressing and Thrusters need to be added.) ---
feature to easily roll "Other Formula
The following tags are the noted instances of needing further data entry features. but I have not gone through all the specials tags.
Professional tag; needs to be updated (perhaps with a text box) to allow details on the profession needed.
Integration tag: needs slot usage data text box
Deconstruction/boost/polarize tag: needs damage text box
Sniper tag: needs distance text box 
shield tag: needs location to place the roll formula. Perhaps in "other formula". If so, see below.
Other Formula: feature to display the roll button on the main sheet, like attack or damage. Instead of just within the chat card

DONE ----(Ammunition
Nanite Capsules: Nanites are not yet an ammo type, nor can they be selected in weapon's ammo type)---

**Comment by Bagenholm** [comment]
Re: Augmentations attack and damage rolls. Also, saving throws.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
