### ISSUE TITLE
[BUG/Feature Request] Unable to use Batteries in Powered Armor

### ISSUE THREAD

**Issue by supernovajm** [foundryvtt-starfinder/foundryvtt-starfinder#505]
If a powered armor is set to use Charges, when you hit the reload button it will split a stack of batteries, but won't slot the battery in the powered armor.

Steps to replicate:

- Drag Sci-Shield Unit Powered armor from compendium
- Set Powered armor to use charges
- hit the "Reload" button on the powered armor while having an appropriate battery in your inventory
- If the battery is in a stack, 1 will be separated, but battery will not be slotted into the armor

**Comment by ian612** [comment]
This is an issue with the item in the compendium, rather than a system bug. The item needs to be set to use charges AND have a container section added that accepts ammunition in order for it to work, but it looks like when it was entered that second part was missed.

**Comment by ian612** [comment]
Completed by #1421
