### ISSUE TITLE
NPC2 and Hazard always have friendly color

### ISSUE THREAD

**Issue by CptTwinkie** [foundryvtt-starfinder/foundryvtt-starfinder#526]
No matter the token setting (friendly/neutral/hostile) NPC2 tokens and Hazard tokens always show the friendly color

In the image below this NPC2 is hostile but is showing a friendly green color
![image](https://user-images.githubusercontent.com/2079751/151728920-6bb238ee-93d6-4c01-8855-f9137babe105.png)

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
