### ISSUE TITLE
REQUEST: Place a pre-configured template for an action

### ISSUE THREAD

**Issue by ILikeCoolThings** [foundryvtt-starfinder/foundryvtt-starfinder#537]
Similar to what 5e and Pathfinder do, it would be nice to have a button under the chat dialogue to set a set template for a spell/ability if applicable.

![image](https://user-images.githubusercontent.com/54457140/152903347-da91e3db-9d3b-4c3c-8976-e83f61b3ec6f.png)

**Comment by Freelancerjw** [comment]
I second this request!

**Comment by ian612** [comment]
This is now implemented as of 0.25.2
