### ISSUE TITLE
Feature Request: Armor Upgrades & Augmentations as Weapon

### ISSUE THREAD

**Issue by sturteva** [foundryvtt-starfinder/foundryvtt-starfinder#550]
I'm working on adding some Junker's Delight items to the compendium. The [scrap spikes](https://www.aonsrd.com/ArmorUpgrades.aspx?ItemName=Tactical&Family=Scrap%20Spikes) act as weapons and there is not currently the weapon relevant sections in Armor Upgrades "Details" Tab to easily be used as a weapon. 

After a quick inspection to see if the weapon augments like Optical Laser or Bone Blade handled the weapon sections, I discovered that they didn't either. 

Please update both Augmentation & Armor Upgrades to handle the potential of being a weapon as well. I imagine the best way to handle that would be to treat it similar to how Power Armor handles it?

**Comment by ian612** [comment]
This has been completed by #1108
