### ISSUE TITLE
Containers on NPCs return NaN bulk

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt-starfinder/foundryvtt-starfinder#554]
![image](https://user-images.githubusercontent.com/77904738/154854180-5ed0c5e6-cd51-4682-ac94-8198e4df20d9.png)
Add a Null Space Chamber to an NPC and put an item in it, the container bulk will show as NaN.

**Comment by MLPMDog** [comment]
It happens to players as well! It also makes an error about wealth.

**Comment by LebombJames** [comment]
This was a separate issue, yours has been fixed on V10. This may have too? idk

**Comment by MLPMDog** [comment]
Nope, I have the most updated version, that's why I commented since it was still open. Does this in every world even the test and always gives this.
![image](https://user-images.githubusercontent.com/55165669/193952177-00d50eb5-9f3a-46c5-a601-8e4f04a7dace.png)

**Comment by LebombJames** [comment]
Sorry, it's fixed on dev but not released yet I meant. That error is also for something else entirely

**Comment by MLPMDog** [comment]
Ah fair enough, well this is a bug that's happening lol XD Hope it gets fixed and updated then!

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
