### ISSUE TITLE
Armor speed modifier units not in localization file

### ISSUE THREAD

**Issue by aldarion-jdr** [foundryvtt-starfinder/foundryvtt-starfinder#558]
Hi !
It appears that units for an armor item speed modifier cannot be changed in the localization file.
Is it hard coded in the armor sheet?

Thank you for your help.

**Comment by ian612** [comment]
Hi, it may have been before but as of now it is not hardcoded, it's determined under `SFRPG.Units.Speed`

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
