### ISSUE TITLE
Items with a level of 0 become uneditable

### ISSUE THREAD

**Issue by drenghel** [foundryvtt-starfinder/foundryvtt-starfinder#576]
Versions: Latest at the time, Foundry 9 255, SFRPG 0.18.2

Hi, 
as said in the title I can't **sometimes** edit fields (but most of the time, the field resets itself on it's own instantly) on:

- NPC Sheets
- Characters Sheets

and it happens on (**sometimes**):
- items that have been dragged from SRD (e.g. a Club don't work most of the time)
- New Goods (from the + buttons)

It happens on my heavily modded World AND on an empty one, on a empty char.

Sorry for the lack of precision, I tried a bunch of things, and asked for help on Discord, it's really confusing.

**Comment by wildj79** [comment]
I've played around with creating items a bit, and have found that items with a level of 0 are having issues. Definitely a bug in the system.
