### ISSUE TITLE
Mystic Cure

### ISSUE THREAD

**Issue by Carantin** [foundryvtt-starfinder/foundryvtt-starfinder#582]
Hello, I would like to leave a formula that has cost me to get (for not being a programmer) and leave it exposed.
it is the healing formula of the mystic cure spell.
(@item.level+max(sign(@item.level-1),0)+max(sign(@item.level-2),0)+max(sign(@item.level-3),0)+max(sign(@item.level-4),0)+max(sign(@item.level-5),0))d8 + @abilities.wis.mod

**Comment by Iankid** [comment]
(lookupRange(@item.level, 0, 1, 1, 2, 3, 3, 5, 4, 7, 5, 9, 6, 11))d8 + @abilities.wis.mod
would be a simpler version. But this request still helped to no we shouldn't update that.

For explanation, the above formula, it looks for the minimum range of the item level, and uses the next number

**Comment by LebombJames** [comment]
The lookupRange version is currently the formula set in the dev build, so it'll be updated when a new release comes out.

**Comment by Carantin** [comment]
Thanks, 
i´m study programming.
