### ISSUE TITLE
Shield bugs

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#586]
- [x] Equipped shields do not currently add to the AC of a character
- [x] "Shield: +0 / +0" in item tags in description tab always displays "0", no matter the actual bonus.
- [ ] Above issues caused by class automatic proficiency check not active, according to LebombJames
- [ ] Feature Request: Improved visual aid to show alignment bonus

**Comment by LebombJames** [comment]
Ticking proficient on the shield's sheet will cause the correct numbers to be shown, fixing 1 and 2. The issue is that there's no auto proficiency detection so you need to manually tick it for every shield you have.
