### ISSUE TITLE
Modifiers to damage formulas get added to All selected formulas, when multiple selected

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#627]
In situations where there is more then one selectable damage formula. there are cases where both formulas are used.
Example, 6th level Solarian is using his Solar Weapon (2d6 S) with a Electron, Minor Solarian Weapon Crystal (1d4 E).
Currently, any modifiers on the sheets, situational or constant, get applied to both formulas when both selected.
Even deciding to do one formula at a time is tricky, as that asks a player to track down any constant modifiers.

Proposed solution: In the damage window, create a 2nd checkbox for each formula, to dictate if modifiers get added to that roll.
This solution may need some further thought.

**Comment by ian612** [comment]
I believe this was corrected with the addition of primary damage sections https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1231
