### ISSUE TITLE
Feature request: Weapon type attack/damage for non-weapon item attack/damage rolls.

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#661]
There are various abilities or items throughout the system that has the listed attack/damage treated as a specific weapon type (e.g. Advanced Melee weapon).
For the purpose of correctly adding modifiers for these items, I am looking for a means to treat them as such.

2 proposed solutions are: 
Either create an @ reference to look for modifier bonuses, like the @abilities.str.mod reference.
Or a dropdown in item that allows item attack/damage rolls to be treated as listed weapon type.

**Comment by ian612** [comment]
This has been added by #1108
