### ISSUE TITLE
Pre-select triggered level for variable level spell

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt-starfinder/foundryvtt-starfinder#664]
If you trigger mind thrust from level 2 slot, it should pre-select level 2 slot in the spell dialog. Currently it pre-selects level 1 slot instead.

**Comment by mkahvi** [comment]
This might actually be a bug? Since it pre-selects level 1 when I trigger level 2 spells, and it pre-selects level 2 for level 1 spells.

**Comment by LebombJames** [comment]
RAW, you can cast variable level spells using higher level spell slots, but they still have the effects of the level you know it at, e.g you can cast 1st level Mind Thrust using a 2nd level spell slot, so this isn't a bug. The default option is a bit inconvenient though, I agree.

**Comment by mkahvi** [comment]
I know the ability is there, I just wish it pre-selected the level I was trying to cast so I don't need to change it by default.
