### ISSUE TITLE
Technomancer Weapon Specialization is not calculating correctly 

### ISSUE THREAD

**Issue by Leonaquilla** [foundryvtt-starfinder/foundryvtt-starfinder#704]
See attached screenshot of a crit damage roll.    Damage bonus should be 11/2 but it appears to be dividing by 0, turning a 21 on a 4d4 (crit, so rolled twice) into 9. 

![image](https://user-images.githubusercontent.com/108372814/179650607-79b55112-3108-457f-9559-177c1e254e91.png)

**Comment by wildj79** [comment]
It looks like the formula is incorrect to begin with. Most calculations in Starfinder round down, so the use of `ceil()` is incorrect; it should be using `floor()`. Also, it looks like it's subtracting instead of adding. Considering all that, 12 + 9 - 6 - 6 would be 9.

**Comment by Leonaquilla** [comment]
Swapping and replacing it did seem to fix it.     It was dragged and dropped from the compendium so no idea why it was doing that.
