### ISSUE TITLE
Missing Magic Items marked as Worn

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#719]
This is a report to myself, and from anyone who can reply to this.
There are magic items and hybrid, both already in the compendium and not, that are not marked as "Worn" in SRD sites. But are in their books. 
I will be able to access the core line of rulebooks to learn about "Worn" magic and hybrid items from those. But magic and hybrid items from APs, Single adventures, and SFS, I will need replies from people who own them, to list off "Worn" magic and hybrid items, as displayed in your books.

**Comment by byglad** [comment]
Attack of the Swarm Worn magic items:
Adaptive Swarm Mask (Hybrid item)
Authority Medallion
Courage Medallion
Empty Orbit Emblem
Friendship Bracelet
Glory Medallion
Hoop of Perspicacity
Monocle of Recognition
Robe of Communalism
Valor Medallion

**Comment by Yoonki-boop** [comment]
Drift Crashers #1:
- Araznian Crusader Helm

Drift Crashers #2:
- None

Dead Suns #1
- Iomedaean Crusader Helm

Dead Suns #2
- Ring of Fangs

Dead Suns #3
- None

Dead Suns #4
- Celestial Stole
- Eohi Boots

Dead Suns #5
- Dust Goggles
- Gravitic Modulator
- Plant Shield Amulet
- Redundancy Belt
- Remote Surveyor

Dead Suns #6 
- None

**Comment by Yoonki-boop** [comment]
Dawn of Flame #1:
- Allegiance Collar
- Telespectrum Circlet (can be installed as an armor upgrade)
- Flame Shield Gauntlet

Dawn of Flame #2:
- Pilot's Helmet
- White Knuckle Gloves
- Radiant Ensemble
- Shattercoat

Dawn of Flame #3:
- None

Dawn of Flame #4:
- Breath-Stealer Mask (can be installed as an armor upgrade)
- Soul Projector (can be installed as an armor upgrade)
- Eldritch Encephalon
- Weatherwear
- Conqueror's Star of the Headless Vesk
- Hivejack

Dawn of Flame #5:
- None

Dawn of Flame #6:
- Void Hag Robe
- The Malikah's Robes

Against the Aeon Throne #1:
- Motion-Detection Badge

Against the Aeon Throne #2:
- None

Against the Aeon Throne #3:
- None

**Comment by Yoonki-boop** [comment]
Signal of Screams #1:
- None

Signal of Screams #2:
- Ring of the Ninth Truth

Signal of Screams #3
- None

The Threefold Conspiracy #1:
- None

The Threefold Conspiracy #2:
- None

The Threefold Conspiracy #3:
- Intonation Pendant

The Threefold Conspiracy #4:
- Night hag's Heartstone functions as a lv9 worn magic item, but disappears after 24 hours. So not a real item, but sorta..?

The Threefold Conspiracy #5:
- None

The Threefold Conspiracy #6:
- None

Devastation Ark #1:
- None

Devastation Ark #2:
- Arcane Signet

Devastation Ark #3:
- Entanglement Belt (Pair) 
- Quantum Pad
- Quantum Processor

**Comment by Yoonki-boop** [comment]
Liberation of Locus-1:
- Azlanti Noble's Cloak

Junker's Delight:
- None

Great Grav Train Robbery:
- None

Band on the Run:
- None

System Takedown:
- None

Redshift Rally:
- None

Before the Storm:
- None

**Comment by Yoonki-boop** [comment]
First Contact:
- None

Skitter Crash, Skitter Shot, Skitter Home:
- None, None, None

The Starfinder Four vs the Hardlight Harlequin:
- None

Bounties #1, 2, 3 and 4:
- None, None, None and None.
