### ISSUE TITLE
Spells and Character sheets not opening

### ISSUE THREAD

**Issue by TheBigBadSalad** [foundryvtt-starfinder/foundryvtt-starfinder#723]
After the latest update to foundry, the starfinder game system wont open any spells, old or newly created. The character sheets wont open either, newly created or old either.

Foundry Virtual Tabletop: Version 10, 10.283
Game System: sfrpg, 0.19.1
Active Modules: 0
Performance Mode: 2

**Comment by TimToxopeus** [comment]
That is to be expected. The system is not yet prepared for v10. I recommend keeping v9 installed (if not on the side) until an update is released.
