### ISSUE TITLE
Browse Equipment Sort by Level doesn't sort correctly

### ISSUE THREAD

**Issue by byglad** [foundryvtt-starfinder/foundryvtt-starfinder#729]
Looking at the Compendium, click on the Equipment on the bottom and search with the sort by of level.

![CompendiumEquipSearchSortByLevelBug](https://user-images.githubusercontent.com/45810407/189188058-e01d7a1b-b99e-4531-9dba-047d8b3b307a.png)

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
