### ISSUE TITLE
Max Resolve Points not calculated correctly

### ISSUE THREAD

**Issue by cmleinz** [foundryvtt-starfinder/foundryvtt-starfinder#731]
Core Rulebook p. 22

> You have a number of Resolve Points equal to half your character level (rounded down, but minimum 1) + the modifier of your key ability score.

However the calculation for max Resolve Points on the sheet is done regardless of the players selected key ability score.

![soldier_resolve](https://user-images.githubusercontent.com/103841857/190067864-36b6579f-3b60-402d-8e36-c7b0b448de9d.png)

The above character should have a max Resolve Point pool of 4, since Dex is their selected key ability score. On Page 58:

> Key Ability Score This entry indicates which of the six ability scores is most important for this class—that ability is your key ability score. To be most effective, you should usually make your key ability score your highest ability score. Unless otherwise noted, the saving throw DC for foes to resist your class features (if appropriate) is equal to 10 + half your class level + your key  ability score modifier. This entry also notes one or two other ability scores that are important for this class but are not vital. 

Perhaps I'm not fully understanding the rules, but it sounds like the player has the option of selecting their key ability score, which if true would mean this value should be derived from modifier of the key ability score as selected by the player.

**Comment by Iankid** [comment]
That dropdown is due to be removed. The system draws the KeyAbility from your 1st class item, and can be changed there. There are similar known issues in relation to this though.

**Comment by cmleinz** [comment]
> That dropdown is due to be removed. The system draws the KeyAbility from your 1st class item, and can be changed there. There are similar known issues in relation to this though, if multiclassing.

Ah I see. Great, thank you!

**Comment by wildj79** [comment]
Closing this for now.
