### ISSUE TITLE
Can't access token settings for existing starship actors, prototype or otherwise.

### ISSUE THREAD

**Issue by L0g1cBomb** [foundryvtt-starfinder/foundryvtt-starfinder#738]
When I try to enter the token settings from the actor sheet (for prototype token) or from the token sheet pop-up (for instanced token settings), multiple errors are thrown as follows:

```
RangeError: Maximum call stack size exceeded
[No packages detected]
```
followed by several hundred lines of this error:
```
at Function.getTrackedAttributes (foundry.js:22408)
```

and then finally:
```
at TokenConfig.getData (foundry.js:70149)
    at async TokenConfig._render (foundry.js:5014)
    at async TokenConfig._render (foundry.js:5739)
```

Foundry Version 10.285
SFRPG Version 20.1

**Comment by wildj79** [comment]
Currently fixed on the development branch, will be included in the next release.
