### ISSUE TITLE
When creating a new starship, components cannot be dragged and dropped from compendium.

### ISSUE THREAD

**Issue by L0g1cBomb** [foundryvtt-starfinder/foundryvtt-starfinder#739]
When I tried to access token settings for existing starship actors, it did not work (see Issue #738 ), so I tried to make a new starship actor for each of my existing ones. That solves the token settings issue, but I cannot drag and drop components onto the starship from the compendiums. Doing so throws the following error:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
[Detected 1 package: system:sfrpg]
    at ActorSheetSFRPGStarship._onDrop (starship.js:433)
```

Foundry Version 10.285
SFRPG Version 20.1

**Comment by wildj79** [comment]
This has been fixed on the development branch and will be in the next release.
