### ISSUE TITLE
Reloading weapons fails and causes error

### ISSUE THREAD

**Issue by Grizwold53** [foundryvtt-starfinder/foundryvtt-starfinder#744]
When trying to reload a weapon, or drag and drop ammo onto a weapon, receive the following error in console:

![error](https://user-images.githubusercontent.com/88157602/192113841-84eafcd7-0e0c-48be-8ab0-bac73c04f692.PNG)

When clicking the reload button on the weapon, the proper number of rounds is deducted from the rounds item stack, but it is not reflected on the ammo of the weapon

Before reload:

![before reload](https://user-images.githubusercontent.com/88157602/192114554-5810c50f-3c53-466f-a4ed-41a5daa13c6e.PNG)

After reload:

![after reload](https://user-images.githubusercontent.com/88157602/192114559-db305956-1558-4948-aa8c-b047fe44c31a.PNG)

**Comment by LebombJames** [comment]
Note to self for later: this should be solved by removing a `.data` on line 138. Will PR it when I get a chance

**Comment by wildj79** [comment]
This was fixed during the big data model migration and will be in the next release.
