### ISSUE TITLE
Issues with Mechanic Drone

### ISSUE THREAD

**Issue by Vanarga** [foundryvtt-starfinder/foundryvtt-starfinder#745]
When creating a mechanic drone, it doesn't appear that [drone special abilities](https://www.aonsrd.com/Classes.aspx?ItemName=Drone) show up automatically. When added manually as feats they count against the total. For example: 
Basic mods, limited AI, master control, skill unit, Expert AI, Upgraded power core, etc.

Another drone issue, is adding Weapon Fusions. This does not seem to work on drones (works fine on normal characters), when adding a fusion nothing happens, it does not show up under the weapon.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
