### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'captain')

### ISSUE THREAD

**Issue by Larkinabout** [foundryvtt-starfinder/foundryvtt-starfinder#747]
`setupRollContexts` method in actor.js fails due to undefined `crewActorData` variable.

![image](https://user-images.githubusercontent.com/105953297/193358197-718b9959-c1b4-4da0-94c4-64cefc0d0852.png)

**Comment by wildj79** [comment]
Fixed during the data model migration. Fix will be in the next release.
