### ISSUE TITLE
[Bug] Client Using >4Gb Memory During Migration

### ISSUE THREAD

**Issue by FileMagic** [foundryvtt-starfinder/foundryvtt-starfinder#749]
When migrating to FoundryVTT v10 and up, from previous versions, the migration method causes crashing due to not limiting the maximum amount of memory that the JavaScript can use during migration. On Chrome this will lead to a `error code: out of memory` to come up after migration a larger campaign (this might be due to larger high resolution assets being used I do not know yet).

Steps to Replicate:
1. Create a world with a lot of assets (in my case it was about 4 Gb of data).
2.  Open up browser as GM.
3. Watch Memory rise.
4. Profit???

**Comment by FileMagic** [comment]
The highest I saw was 20 Gb, however it at one point restarted and it seems that it has started the migration again after waiting fro about an hour. This may be fixed in fe38b4f8c7822a42833fd7d27de6b219fea4443d, however I have not tested this nor do I know how to yet.
![image](https://user-images.githubusercontent.com/22534836/193713443-c1746f36-a765-491b-bc89-d5dc47e96482.png)

**Comment by FileMagic** [comment]
I can clearly see that the migration script is running though when I look at the dev console:
![image](https://user-images.githubusercontent.com/22534836/193713787-ac5383c4-9d48-4283-80a7-f791d042317b.png)

**Comment by FileMagic** [comment]
> The highest I saw was 20 Gb, however it at one point restarted and it seems that it has started the migration again after waiting fro about an hour. This may be fixed in [fe38b4f](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/commit/fe38b4f8c7822a42833fd7d27de6b219fea4443d), however I have not tested this nor do I know how to yet. ![image](https://user-images.githubusercontent.com/22534836/193713443-c1746f36-a765-491b-bc89-d5dc47e96482.png)


Also here is a picture of 20Gb just for the laughs:
![image](https://user-images.githubusercontent.com/22534836/193713865-59b8a003-6d18-4f9d-8777-4a00e34ce929.png)

At least I thought it was funny.

**Comment by FileMagic** [comment]
It finally finished, and everything seems to work. However, for the average user who has only about 16-8Gb of ram, this may be an issue.

**Comment by FileMagic** [comment]
Lastly I wanted to say, thank you all for creating this project my group and I definitely had a lot of fun playing using this module!

**Comment by FileMagic** [comment]
I was poking around a bit at the docs and wanted to ask if it would be possible to use this [updateAll](https://foundryvtt.com/api/v10/classes/client.Actors.html#updateAll) method on the game.actor class from [line 21 in migration.js](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/blob/b9a40bcb64deebd0f137ab841c691db7ab5758fc/src/module/migration.js#L21).



If so it seems that scenes, items, messages, and macros have this same method of [updateAll](https://foundryvtt.com/api/v10/classes/client.WorldCollection.html#updateAll) due to them being inherited from [WorldCollection](https://foundryvtt.com/api/v10/classes/client.WorldCollection.html). So this may be one way to handle this a bit cleaner.

I am by no means a javascript developer. So, I apologize if this is dumb.

**Comment by LebombJames** [comment]
While there are definitely better ways to run the migration, you really shouldn't be importing entire compendium into your sidebar

**Comment by FileMagic** [comment]
That is super fair and makes sense. I will tell the DM to stop doing this asap.
