### ISSUE TITLE
Cannot drag actors into a ships crew tab

### ISSUE THREAD

**Issue by NRschwier** [foundryvtt-starfinder/foundryvtt-starfinder#755]
Hello I am unable to drag any PC into the crew section of a starship. There is no error in the console, dragging simply does nothing.

**Comment by Iankid** [comment]
Known issue with V10. Fix is in the works. Temporary solution is to turn the ship into an NPC ship.

**Comment by wildj79** [comment]
Fixed in a70605cd, will be in the next release.
