### ISSUE TITLE
Channel Skill not working

### ISSUE THREAD

**Issue by Locotomo** [foundryvtt-starfinder/foundryvtt-starfinder#762]
Hi there, the Mystics feature "channel skill" doesn´t seem to work. I choose the two skills, but the inside bonus is not added to the skill check. 
(Foundry v10)

**Comment by Locotomo** [comment]
Problem solved. Mystic was Akashic and gets the channel skill at level 1.
Had to change the formula into :
lookupRange(@classes.mystic.levels, 0, 1, 1, 5, 2, 8, 3, 11, 4, 14, 5, 17, 6, 20, 7)

**Comment by wildj79** [comment]
Closing this for now, since it seems to have been resolved.
