### ISSUE TITLE
Creating a circle area via Circle Template causes unresponsive UI

### ISSUE THREAD

**Issue by cmleinz** [foundryvtt-starfinder/foundryvtt-starfinder#763]
Clicking measurement controls, and creating a circular area causes the UI to become unresponsive. Once a circular template has been placed on the map, selecting measurement controls makes it not possible to click any other tooltips, or add tokens to the map. Looking at the console we have the following error each time when clicking a tooltip.

```
Uncaught TypeError: hl is undefined
[Detected 1 package: system:sfrpg]
    highlightGrid https://vtt1.leinz.io/systems/sfrpg/module/template-overrides.js:84
    _refresh https://vtt1.leinz.io/scripts/foundry.js:43896
    refresh https://vtt1.leinz.io/scripts/foundry.js:25113
    highlightObjects https://vtt1.leinz.io/scripts/foundry.js:23997
    deactivate https://vtt1.leinz.io/scripts/foundry.js:30330
    activate https://vtt1.leinz.io/scripts/foundry.js:30299
    _onClickLayer https://vtt1.leinz.io/scripts/foundry.js:67137
    jQuery 2
```

Tested with brand new world and no modules enabled, same result.

**Comment by wildj79** [comment]
Known issue that's already been reported; see #748 and  #736. It has been fixed in the current development branch and will be in the next release.
