### ISSUE TITLE
Items do not show within containers in NPC inventories

### ISSUE THREAD

**Issue by SCMNomad** [foundryvtt-starfinder/foundryvtt-starfinder#779]
Item in NPC's inventory:
![ss1](https://user-images.githubusercontent.com/44250630/198854907-4d0b5fcf-d841-40ca-935a-053e856633a7.png)
Item in PC's inventory:
![ss2](https://user-images.githubusercontent.com/44250630/198854906-62538e57-5ad4-4743-b900-6d4e422db363.png)
Console:
![error](https://user-images.githubusercontent.com/44250630/198854905-6518a982-6867-4f14-9ed6-d280363d56ef.png)

**Comment by SCMNomad** [comment]
Items in NPC's inventory:
![ss1](https://user-images.githubusercontent.com/44250630/198854907-4d0b5fcf-d841-40ca-935a-053e856633a7.png)
Item in PC's inventory:
![ss2](https://user-images.githubusercontent.com/44250630/198854906-62538e57-5ad4-4743-b900-6d4e422db363.png)
Console:
![error](https://user-images.githubusercontent.com/44250630/198854905-6518a982-6867-4f14-9ed6-d280363d56ef.png)

**Comment by wildj79** [comment]
Unfortunately the posted errors are unrelated. If you look through the call stack, it mentions the file `searchanywhere.js` which isn't a part of our codebase. So, it's probably a module trying to access the actor data through `data.data` instead of `system`.

**Comment by SCMNomad** [comment]
> Unfortunately the posted errors are unrelated. If you look through the call stack, it mentions the file `searchanywhere.js` which isn't a part of our codebase. So, it's probably a module trying to access the actor data through `data.data` instead of `system`.

I tested the same thing out in a fresh game, was having the same problem 
![image](https://user-images.githubusercontent.com/44250630/198893997-291cd0c3-d357-421e-a4bf-f5f7f9dd6738.png)
![image](https://user-images.githubusercontent.com/44250630/198894003-8e187cb5-6f4c-4fd9-b01e-a84698c2f415.png)

Here's the whole console after pulling the items out of the compendium:
![image](https://user-images.githubusercontent.com/44250630/198894048-84a19c87-b346-402e-b42c-0553c46fd755.png)
