### ISSUE TITLE
Maintenance Panel Access Ship Action bug.

### ISSUE THREAD

**Issue by sothicus01** [foundryvtt-starfinder/foundryvtt-starfinder#793]
There is a bug with the Maintenance Panel Access ship action. It seems to be attempting to roll 1d0 instead of 1d20. A double window seems to pop up and when you roll, nothing occurs in the chat. On closer inspection, the roll code appears to be attempting to roll a 1d0.

**Comment by notPronoe** [comment]
Could you point to the code where it attempts to roll a d0?

Also are you still experiencing this issue? What version of the system are you using? current release is `0.21.1`

I've tried triggering the `Maintenance Panel Access` action myself and it works as intended, the roll was using a d20 + the appropriate modifiers.

**Comment by ian612** [comment]
Closed as part of old issue cleanup. If you believe this issue hasn't yet been addressed, please re-open it and leave a new comment.
https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/discussions/1148
