### ISSUE TITLE
Item Piles module no longer works after update to foundry v10 and the latest version of SFRPG

### ISSUE THREAD

**Issue by TheGreatRedDuke** [foundryvtt-starfinder/foundryvtt-starfinder#802]
After updating to Foundry v10 and the latest version of the SFRPG system, the Item Piles module no longer functions.

When dropping an item to the canvas, the Item Piles dialog does not appear, double clicking open the pile opens a sheet I don't think is correct, and closing that sheet breaks the item icon and the very token itself. I'm running this in a fresh v10 install (build v288) using the Starfinder game system (v0.20.3). The only modules running are: Item Piles, socketlib, libwrapper, and Advanced Macros. I've verified they are all running their lates versions. No console errors are produced. I'll include a screen shot of all console messages generated during the described test.

I asked about this issue on the Item Piles project, and they indicated the issue probably lies in the SFRPG implementation. They said to ask "whether it is possible to disable the [SFRPG's] item drop in any way, if there is not, item piles is probably not going to be compatible with Starfinder, at least not the item drop portion of the module."

Item Piles did previously work on Foundry v9 with the last version of SFRPG before the v10 upgrade.

Some of the strange behavior may be related to/duplicating the issue described in [Dropped items on map break on open. #795](https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/issues/795).

_To Reproduce:_

1. Create a new scene (gave it a generic BG image)
2. Open the Equipment Browser
3. Dragged an item from the Equipment Browser to the game canvas (no Item Piles dialog appears)
4. Double click the item to open sheet (I don't think this is the correct sheet)
5. Close the sheet (icon breaks)
6. Double click to re-open the item (token actor doesn't exist warning appears)
7. Expected behavior
8. I expected the Item Piled dialog to appear then I dropped the item initially, and I expected the sheet that opens when double clicking to be an Item piles sheet.

_Screenshots:_

![01](https://user-images.githubusercontent.com/78890368/201537707-995534e6-eea3-4075-bf5d-d79edba2dc34.jpg)
![02](https://user-images.githubusercontent.com/78890368/201537709-59223e27-ceac-4fa0-99ef-5266121c8439.jpg)
![03](https://user-images.githubusercontent.com/78890368/201537710-5950b7f1-19d5-4eb2-b118-51ee88819bdb.jpg)
![04](https://user-images.githubusercontent.com/78890368/201537713-f0477527-5c9c-483e-8973-53169670fa1e.jpg)
![05](https://user-images.githubusercontent.com/78890368/201537717-a59cdb2b-9df0-4869-99c8-3583f4bf5529.jpg)

**Describe the solution you'd like**

I would like the Item Piles to functions as expected; for the IP dialog to appear when dropping the item initially, and the sheet that opens when double clicking to be an Item piles sheet.

**Additional context**

_Setup:_

- Foundry Version: v10.288
- System Version: sfrpg v0.20.3 (Starfinder)
- Item Piles Version: v2.2.10
- Browser & version: Local Foundry install

_Active modules:_

- Item Piles v2.2.10
- libwrapper v1.12.10.0
- socketlib v1.0.12
- Advanced Macros v1.17.3

**Comment by Dosendusche** [comment]
I believe this was fixed already in this PR: https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/847
I know this looks like a different issue but the bug was about the image link being broken inside the collection sheet and fixed within the same PR.
