### ISSUE TITLE
NPC tokens unable to see other tokens - vision detection mode set to basic range 0 by default

### ISSUE THREAD

**Issue by ahoward-cf** [foundryvtt-starfinder/foundryvtt-starfinder#824]
**Describe the bug**
When new NPC sheets are created, or existing compendium Aliens are imported, their vision type (darkvision, lowlight) is set correctly, with the appropriate distance, but they are also created with a default detection mode of "Basic Vision" with a range of "0 ft" and "Enabled". This means that when selected, a dark vision NPC can see the map out to their range, but are unable to see any tokens, even if they are 5 ft away. 

**To Reproduce**
Create an NPC manually, using the statblock parser module, or via compendium import. Drag a token onto a scene with several other tokens, select the NPC token.

This may be an update bug and therefore may also require an existing world to be created in v0.20.3, then update the world to v0.21.1. The NPCs do not need to have been created prior to the update. This bug also existed in v0.20.1. I cannot say if it existed before that. 

**Expected behavior**
NPCs without explicit detection modes should be created with no detection modes. An appropriate detection mode matching their vision will be created upon token drop. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29404906/203537181-f3bd6d1d-e002-45e5-9def-59ffa2cf0f2e.png)

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: Desktop version of Foundry
 - Foundry Version: 288
 - SFRPG Version: 0.21.1

**Comment by LebombJames** [comment]
What do your default prototype token settings look like?

**Comment by LebombJames** [comment]
Additionally, could you try on Foundry 10.290?

**Comment by ahoward-cf** [comment]
Interesting. Looks like because I have default vision enabled, it is also giving a default detection method. You only have my word for it of course but I never set a detection mode for default prototype tokens: 

![image](https://user-images.githubusercontent.com/29404906/203611594-0a91f688-9a67-4621-a5bf-7380cce6b80b.png)

Potentially an world update bug?

**Comment by ahoward-cf** [comment]
> 

Got a session tonight, wont risk updating foundry until its over. Not enough time for a backup and restore if it goes wrong.
