### ISSUE TITLE
Actions added to items

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#837]
Different items Hybrid/Magic/Tech/Goods can have need for the actions item menu, to track active state, or to track usage.
Also there are some items that have both passive and active effects, and currently there aren't modifiers that can remain on while an item is inactive

Actions menu should be added to said items, including the consumable usage settings that consumables have.
A new modifier type that can be constant even if an active feature/item is off, would solve passive effects that should remain even while a item's active state is off.

**Comment by ian612** [comment]
This is partially implemented in https://github.com/foundryvtt-starfinder/foundryvtt-starfinder/pull/1108

**Comment by LebombJames** [comment]
Gonna assume this was closed by #1108
