### ISSUE TITLE
Temp HP is always deleted when applying damage, and causes stamina to behave oddly

### ISSUE THREAD

**Issue by LebombJames** [foundryvtt-starfinder/foundryvtt-starfinder#848]
**Describe the bug**
When applying damage to actors with Temp HP, the Temp HP is always reduced to 0 no matter the damage, additionally, stamina seems to be changed by (the number of Temp HP the actor had - the incoming damage), which can cause it to go up or down.

**To Reproduce**
Apply damage to an actor with Temporary HP

**Expected behavior**
The Temp HP should be subtracted by the amount of incoming damage

**Screenshots**

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chome
 - Foundry Version: 10.291
 - SFRPG Version: 0.22.0

**Additional context**
Also occurs on 0.21.0

**Comment by Dosendusche** [comment]
I also had this problem in one of my sessions. Kinda personal interest.
I will take a look at that.
