### ISSUE TITLE
Create a second text box for 'Short Description' on Item & Actor typed Entities.

### ISSUE THREAD

**Issue by JayBWalker** [foundryvtt-starfinder/foundryvtt-starfinder#87]
We discussed this months ago and never put it here. Just remembered about it, so here goes:

I would greatly value the addition of a second 'Description' box field for Item and Actor type Entities, so that a shorter and more succinctly informative dialogue can be drawn from when posting them as a Chat Card.

As it stands, some Entities have absolutely gargantuan descriptions by necessity. Allowing a second 'short style' description field which the Chat Cards pull from, it would allow you to segregate fast information from full information in a much cleaner way.

This could also be used in a variety of useful ways by players themselves to input any important info they want to mark down as an extra.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Create a second text box for 'Short Description' on Item & Actor typed Entities](https://trello.com/c/bMvqOoOf/40-feat-create-a-second-text-box-for-short-description-on-item-actor-typed-entities)
