### ISSUE TITLE
Configure Floating Numbers Settings Will Not Open - Validation Error

### ISSUE THREAD

**Issue by ThePrisoner31** [foundryvtt-starfinder/foundryvtt-starfinder#903]
**Describe the bug**
Within settings, the 'Configure Floating Numbers Settings' nested under 'Starfinder' does nothing. Console shows a validation error.

**To Reproduce**
Navigate to 'Game Settings', 'Configure Settings', then 'Starfinder', and click on the button 'Configure Floating Number Settings'.

**Expected behavior**
A menu should pop-up allowing configuration of floating number settings. 

**Screenshots**
![Foundry Starfinder Floating Numbers Issue](https://user-images.githubusercontent.com/72581160/210594295-46f79c16-e5ac-4f4b-80cf-165e083d46b7.PNG)

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: electron app (Tested in Chrome as well, same issue)
 - Foundry Version: 10.291
 - SFRPG Version: 0.22.0

**Additional context**
This was first discovered on primary world with 50+ active modules then repeated on a test world with no active modules to confirm the issue is not module dependent.

**Comment by LebombJames** [comment]
Found this one recently and it's already fixed 🙂
