### ISSUE TITLE
Missing Competence bonus type in modifiers list

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#906]
Alongside the Insight, Racial, Circumstance Ect. Bonus types, there should also be Competence.
Example being the Corpseskin Augmentation:
```The necrograft grants a +5 competence bonus to Disguise checks to impersonate corporeal```

This could be addressed in #880

**Comment by Dosendusche** [comment]
After asking i got told that the competence bonus is leftover "pf1eism" and that should be insight.
Looking into the bonus rules: https://aonsrd.com/Rules.aspx?ID=154 competence is not listed but insight is explained with competence.
