### ISSUE TITLE
Doshakari series weapons Incorrect damage formula

### ISSUE THREAD

**Issue by TheGreatRedDuke** [foundryvtt-starfinder/foundryvtt-starfinder#922]
**What item is incorrect/missing?**
All the Doshakari series weapons (advanced, molecular rift, tactical, ultrathin, and zero-edge) have a misconfigured damage formula I believe.

**What book is the item from? What page is it on? If possible, include an Archives of Nethys link**
Near Space pg. 149 | [Doshakari, Tactical](https://aonsrd.com/WeaponDisplay.aspx?ItemName=Tactical&Family=Doshakari)

**SFRPG system version**
0.22.1

**How is it incorrect?**
The damage formulas have the damage dice, but are all missing the " + @abilities.str.mod". They are fairly standard advanced melee weapons and I can't find anything about them that indicates they shouldn't have the strength mod applied.

**What correction should be made?**
Damage formulas for all these should be "[damage dice] + @abilities.str.mod".

**Comment by Iankid** [comment]
A lot of older items seem to be missing this. Thanks for catching it. Running across more, let us know.
