### ISSUE TITLE
Missing Themes from Drift Crisis

### ISSUE THREAD

**Issue by jbronner1972** [foundryvtt-starfinder/foundryvtt-starfinder#934]
Crisis Refugee (DC pg. 38), Drift Crashed (DC. pg. 39), Planar Traveller (Drift Crashers Perfect Storm pg. 47), and Spectra Scion (DC pg. 41) missing from Themes Compendium.

Source
Drift Crisis and Drift Crashers Perfect Storm

Core install is SFRPG 0.22.1

**Comment by jbronner1972** [comment]
Links: 
Crisis Refugee https://aonsrd.com/Themes.aspx?ItemName=Crisis%20Refugee
Drift Crashed https://aonsrd.com/Themes.aspx?ItemName=Drift%20Crashed
Planar Traveller https://aonsrd.com/Themes.aspx?ItemName=Planar%20Traveler
Spectra Scion https://aonsrd.com/Themes.aspx?ItemName=Spectra%20Scion

**Comment by Theleruby** [comment]
This is still an issue.
