### ISSUE TITLE
Misplaced Racial Bonuses

### ISSUE THREAD

**Issue by Toxxyc** [foundryvtt-starfinder/foundryvtt-starfinder#938]
Android Racial Feature "Exceptional Vision" contains improper Modifiers from "Skilled" (Aasimar) racial bonus

- Skilled diplo +2
- Skilled percep +2
![Screenshot 2023-01-22 015005](https://user-images.githubusercontent.com/7594885/213909636-e91ae396-8ace-46cc-a2c0-d63fb36a950e.png)

**Comment by LebombJames** [comment]
Already fixed by #930
