### ISSUE TITLE
Equipment Heavy Armor and Power Armor Filters give 0 results

### ISSUE THREAD

**Issue by ian612** [foundryvtt-starfinder/foundryvtt-starfinder#947]
**Describe the bug**
When using the compendium browser for equipment, checking the box to filter to Heavy Armor or Power Armor returns 0 results. Light Armor works fine. If all armor is selected, I can see sets of Light Armor and Heavy Armor, so the items are in the compendium, they just don't show up properly in the filter.

**To Reproduce**
Open the equipment browser, select the check box for either heavy armor or power armor

**Expected behavior**
Heavy Armor items in the compendium appear

**Screenshots**

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox & Chrome
 - Foundry Version: 10.291
 - SFRPG Version: 0.22.1

**Comment by LebombJames** [comment]
Already fixed on dev #910
