### ISSUE TITLE
Can't create new hazard or vehicle actors

### ISSUE THREAD

**Issue by J-Dawe** [foundryvtt-starfinder/foundryvtt-starfinder#956]
**Describe the bug**
Whenever I try to create a new hazard or vehicle actor, I get an error
Cannot read properties of undefined (reading 'length')

**To Reproduce**
Go to the actors tab, select "Create Actor", choose either Hazard or Vehicle for type, then select "Create New Actor"

**Expected behavior**
A new actor of either the hazard or vehicle variety is created.

**Technical details (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Foundry Version: 10.291
 - SFRPG Version: 0.22.1

**Comment by LebombJames** [comment]
I cannot reproduce this when using firefox
