### ISSUE TITLE
Additional Right click options for chat damage

### ISSUE THREAD

**Issue by Iankid** [foundryvtt-starfinder/foundryvtt-starfinder#958]
Similar to "Apply as Healing", additional options for Apply as Stamina, and Apply as Temp HP would be helpful.
Additional option for Apply as Healing & Stamina might be considered as well.

**Comment by Dosendusche** [comment]
From the current game i'm running we discovered that for the "Medic" archetype it would be usefull to have one that applies to HP if there would be "overhealing" it applies the rest to stamina.
