### ISSUE TITLE
Allow Skill Checks as an Item Output card option.

### ISSUE THREAD

**Issue by JayBWalker** [foundryvtt-starfinder/foundryvtt-starfinder#97]
As titled. There's an abundance of features which include Skill rolls against CR-appropriate DCs but cost Initiative relevant actions (standard, move, etc) and it would be wonderful to be able to include them as Active Features (Items) within a character sheet for easy and clear usage.

Example: Trick Attack as a Feature, specifying the Skill being used (with a +4 Bonus likely via Specialisation) with a shorthand mention for the static DC it targets.
Usable with its own clearly defined Chat Card when you click the 'Attack' or 'Damage' button (where distinct). Perhaps if necessary call it a 'Use' Button.

**Comment by wildj79** [comment]
I’ve considered making modifiers an item type. If I did this, what you describe would definitely be possible. I think I want to hold off on doing anything with this until we see what the new dynamic effects system in Foundry v0.7.0 looks like, though.

**Comment by wildj79** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[FEAT] Allow Skill Checks as an Item Output card option](https://trello.com/c/dfjzuBrt/44-feat-allow-skill-checks-as-an-item-output-card-option)
